version: "3"
services:
  web:
    build: .
    environment:
      - NODE_ENV=development
      - MYSQL_DATABASE_URL=mysql://admin:admin@db:3306/resizer
      - REDIS_URL=redis://redis:6379
    ports:
      - 1337:1337
    command: npm run dev
    volumes:
      - ./:/app
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=resizer
  redis:
    image: redis
volumes:
  db_data:
